### ISSUE TITLE
Subvenster “search Variable”[bug]

### ISSUE THREAD

**Issue by Louy5710** [edwig/Kwatta#3]
Wanneer je een variabele aanmaakt, deze opslaat en vervolgens de naam hiervan wijzigt (bijvoorbeeld variabele “Test” naar “test”), dan dit venster afsluit en weer opent, dan zie je deze variabele 2 keer erin staan (originele naam en gewijzigde naam). Zie blauw gemarkeerd in bijlage.
![image](https://user-images.githubusercontent.com/99489538/153611457-b72ddb33-df42-4752-a7ae-a1381a0a1875.png)

**Comment by edwig** [comment]
Parameters/variables are now stored case-insensitive. As soon as you try to enter a duplicate name the application WILL warn you!
