### ISSUE TITLE
Mogelijk om meerdere testsuites aan te maken binnen een project [wens]

### ISSUE THREAD

**Issue by Louy5710** [edwig/Kwatta#5]
Het lijkt alsof het niet mogelijk is om binnen een project meerdere testsuites aan te maken.
o	Als dit klopt, vind ik het een minimale eis dat dit mogelijk wordt voor het overzicht.
o	Als dit incorrect is, zou ik graag een heldere uitleg in de handleiding willen zien hoe dit uit te voeren.

**Comment by edwig** [comment]
A 'testsuite' is that what once was called a project. Now that projects are gone. this issue is no longer valid.
