### ISSUE TITLE
Subvenster “Search Variable” > knop "Use" [wens]

### ISSUE THREAD

**Issue by Louy5710** [edwig/Kwatta#7]
De knop “Use” heeft een onduidelijke benaming. Ik zou graag een logische benaming willen zien (Bijvoorbeeld “Ok”) en anders een duidelijke beschrijving in de handleiding waar deze knop voor dient.

**Comment by edwig** [comment]
There will be no manual. The button USE has the function to USE the variable in the underlying window. OK is meant to close the window without using the variable. When this button was named "OK" the workings lead to much consternation and confusion.
