### ISSUE TITLE
Handleiding > Verborgen wachtwoord procedure [wens]

### ISSUE THREAD

**Issue by Louy5710** [edwig/Kwatta#9]
De uitleg over de verborgen wachtwoord procedure vind ik onvoldoende toereikend.
Ik weet niet hoe ik een omgevingsvariabele aanmaak in Windows.

**Comment by edwig** [comment]
The suite dialog now has a field to show the hidden password for 3 seconds and a button to show it.
Next to it is a link to the microsoft documentation to set an environment variable. The hover text reveals to set the "KWATTA_PASSWORD" variable with "setx /m"
